@startuml

class Rental {
 daysRented: int
 getCharge(): double
}

class Movie {
title: String
priceCode: int

}

class Customer {
 + statement(): String
}

Customer "1" -left-> "*" Rental
Rental "1" -left-> "*" Movie

@enduml